# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: femllm.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'femllm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66\x65mllm.proto\x12\x06\x66\x65mllm\"s\n\x0e\x46orwardRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x15\n\rhidden_states\x18\x02 \x01(\x0c\x12\r\n\x05shape\x18\x03 \x03(\x05\x12\x14\n\x0cposition_ids\x18\x04 \x03(\x05\x12\x11\n\tlayer_idx\x18\x05 \x01(\x05\"7\n\x0f\x46orwardResponse\x12\x15\n\rhidden_states\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\"\"\n\x0cResetRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"\x0f\n\rResetResponse2\xbc\x01\n\rWorkerService\x12:\n\x07Prefill\x12\x16.femllm.ForwardRequest\x1a\x17.femllm.ForwardResponse\x12\x39\n\x06\x44\x65\x63ode\x12\x16.femllm.ForwardRequest\x1a\x17.femllm.ForwardResponse\x12\x34\n\x05Reset\x12\x14.femllm.ResetRequest\x1a\x15.femllm.ResetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'femllm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FORWARDREQUEST']._serialized_start=24
  _globals['_FORWARDREQUEST']._serialized_end=139
  _globals['_FORWARDRESPONSE']._serialized_start=141
  _globals['_FORWARDRESPONSE']._serialized_end=196
  _globals['_RESETREQUEST']._serialized_start=198
  _globals['_RESETREQUEST']._serialized_end=232
  _globals['_RESETRESPONSE']._serialized_start=234
  _globals['_RESETRESPONSE']._serialized_end=249
  _globals['_WORKERSERVICE']._serialized_start=252
  _globals['_WORKERSERVICE']._serialized_end=440
# @@protoc_insertion_point(module_scope)
